name: Android UI Tests

on: pull_request

jobs:
  android-ui-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          # in current docs of reactivecircus, the script is
          # ./gradlew connectedCheck
          script: ./gradlew app:connectedCheck
          emulator-build: 7425822 # https://github.com/ReactiveCircus/android-emulator-runner/issues/160
