name: Android Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'


      - name: Build Project
        run: ./gradlew assemble

      - name: Run Tests
        run: ./gradlew test