name: Danger Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request' # if only run pull request when multiple trigger workflow



    steps:
      - uses: actions/checkout@v3

#setup JDK for gradle
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically


      - name: Danger Checks
        run: |
          gem install bundler
          bundle install
          bundle exec danger
#               seems to be added later in the project
#          ./gradlew dependencyUpdates


        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}